-- MySQL Script generated by MySQL Workbench
-- Tue Aug 31 21:26:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema e2095613
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema e2095613
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e2095613` DEFAULT CHARACTER SET utf8;
USE `e2095613`;
-- -----------------------------------------------------
-- Table `e2095613`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Role` (
  `id` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_id` TINYINT DEFAULT 1,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Country` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `iso` CHAR(2) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Profile` (
  `user_id` INT UNSIGNED NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT 'https://res.cloudinary.com/dwhnxncff/image/upload/v1630695701/stampee/users/default_profile.jpg',
  `public_id` TINYTEXT NULL,
  `firstname` VARCHAR(80) NULL,
  `lastname` VARCHAR(100) NULL,
  `dob` DATE NULL,
  `country_id` TINYINT UNSIGNED NULL,
  INDEX `fk_Profil_Country1_idx` (`country_id` ASC),
  INDEX `fk_Profile_User1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_Profil_Country1` FOREIGN KEY (`country_id`) REFERENCES `e2095613`.`Country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_User1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`ResetPasswordToken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`ResetPasswordToken` (
  `token` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `user_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`token`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  INDEX `belongsTo_idx` (`user_Id` ASC),
  CONSTRAINT `belongsTo` FOREIGN KEY (`user_Id`) REFERENCES `e2095613`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Category` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`StampCondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`StampCondition` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Theme` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Auction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `start_price` INT NOT NULL,
  `published` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Auction_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Auction_User1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Stamp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Stamp` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `year` YEAR NOT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `createdAt` DATETIME NOT NULL,
  `country_id` TINYINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `condition_id` TINYINT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `theme_id` TINYINT UNSIGNED NOT NULL,
  `auction_id` INT UNSIGNED NULL,
  INDEX `fk_Stamp_Country_idx` (`country_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Stamp_Category_idx` (`category_id` ASC),
  INDEX `fk_Stamp_Condition_idx` (`condition_id` ASC),
  INDEX `fk_Stamp_User_idx` (`user_id` ASC),
  INDEX `fk_Stamp_Theme1_idx` (`theme_id` ASC),
  INDEX `fk_Stamp_Auction1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_Timbre_Pays1` FOREIGN KEY (`country_id`) REFERENCES `e2095613`.`Country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Timbre_Categorie1` FOREIGN KEY (`category_id`) REFERENCES `e2095613`.`Category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_Condition1` FOREIGN KEY (`condition_id`) REFERENCES `e2095613`.`StampCondition` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_User1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_Theme1` FOREIGN KEY (`theme_id`) REFERENCES `e2095613`.`Theme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `e2095613`.`Auction` (`id`) ON DELETE
  SET NULL ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `auction_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_Auction1_idx` (`auction_id` ASC),
  INDEX `fk_Comment_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Comment_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `e2095613`.`Auction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_User1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Image` (
  `stamp_id` INT UNSIGNED NOT NULL,
  `url` TINYTEXT NOT NULL,
  `public_id` TINYTEXT NOT NULL,
  INDEX `fk_Image_Stamp1_idx` (`stamp_id` ASC),
  PRIMARY KEY (`stamp_id`),
  CONSTRAINT `fk_Image_Stamp1` FOREIGN KEY (`stamp_id`) REFERENCES `e2095613`.`Stamp` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Offer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `auction_id` INT UNSIGNED NOT NULL,
  `current_price` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Offer_Auction1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_Offer_User1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offer_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `e2095613`.`Auction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Follow` (
  `user_id` INT UNSIGNED NOT NULL,
  `follower_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `follower_id`),
  INDEX `fk_Follow_Profile2_idx` (`follower_id` ASC),
  CONSTRAINT `fk_Follow_Profile1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Follow_Profile2` FOREIGN KEY (`follower_id`) REFERENCES `e2095613`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Favorite` (
  `user_id` INT UNSIGNED NOT NULL,
  `auction_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `auction_id`),
  INDEX `fk_Favorites_Auction1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_Favorites_Profile1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `e2095613`.`Auction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `e2095613`.`Filters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2095613`.`Filters` (
  `user_id` INT UNSIGNED NOT NULL,
  `theme_id` VARCHAR(255) NULL,
  `country_id` VARCHAR(255) NULL,
  `category_id` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_Filters_Profile1` FOREIGN KEY (`user_id`) REFERENCES `e2095613`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
-- -----------------------------------------------------
-- Dumping data Role
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Role`(id, name)
VALUES(1, "Membre"),
  (2, "Administrateur");
-- -----------------------------------------------------
-- Dumping data User
-- -----------------------------------------------------
INSERT INTO `e2095613`.`User` (
    id,
    username,
    email,
    password,
    role_id,
    createdAt
  )
VALUES (
    1,
    'Joel',
    'joel@test.com',
    '$2y$10$wDgbu/O8srsn4iUr6Xg/9uYL1flxMruF737N.AVC5NbbpxKhKJYXK',
    1,
    '2021-09-06 00:45:14'
  ),
  (
    2,
    'Pier2208',
    'p.leroy.mtl@gmail.com',
    '$2y$10$qT5/7Zu73XU72RZwNYUkJ.FArd3CnhXlLzw9IH/7sMLu7Qcdc.SXi',
    1,
    '2021-09-06 00:50:19'
  ),
  (
    3,
    'Jojo',
    'jojo@test.com',
    '$2y$10$8Tx8/8EcprnFC3OIfDT6ZOsTpW3nFwjiYzA7qWn34UdnkaB/I4H22',
    1,
    '2021-09-06 00:55:59'
  ),
  (
    4,
    'Baracuda',
    'baracuda@test.com',
    '$2y$10$i0DJqqWcRoUzS3pGyRfsEulSQUOj33KQrCftoi/iFSIWJC7HKEql2',
    1,
    '2021-09-06 19:48:52'
  );
-- -----------------------------------------------------
-- Dumping data Country
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Country`(name, iso)
VALUES ('Afghanistan', 'AF'),
  ('Albania', 'AL'),
  ('Algeria', 'DZ'),
  ('American Samoa', 'AS'),
  ('Andorra', 'AD'),
  ('Angola', 'AO'),
  ('Anguilla', 'AI'),
  ('Antarctica', 'AQ'),
  ('Antigua and Barbuda', 'AG'),
  ('Argentina', 'AR'),
  ('Armenia', 'AM'),
  ('Aruba', 'AW'),
  ('Australia', 'AU'),
  ('Austria', 'AT'),
  ('Azerbaijan', 'AZ'),
  ('Bahamas', 'BS'),
  ('Bahrain', 'BH'),
  ('Bangladesh', 'BD'),
  ('Barbados', 'BB'),
  ('Belarus', 'BY'),
  ('Belgium', 'BE'),
  ('Belize', 'BZ'),
  ('Benin', 'BJ'),
  ('Bermuda', 'BM'),
  ('Bhutan', 'BT'),
  ('Bosnia and Herzegovina', 'BA'),
  ('Botswana', 'BW'),
  ('Bouvet Island', 'BV'),
  ('Brazil', 'BR'),
  ('British Indian Ocean Territory', 'IO'),
  ('Brunei Darussalam', 'BN'),
  ('Bulgaria', 'BG'),
  ('Burkina Faso', 'BF'),
  ('Burundi', 'BI'),
  ('Cambodia', 'KH'),
  ('Cameroon', 'CM'),
  ('Canada', 'CA'),
  ('Cape Verde', 'CV'),
  ('Cayman Islands', 'KY'),
  ('Central African Republic', 'CF'),
  ('Chad', 'TD'),
  ('Chile', 'CL'),
  ('China', 'CN'),
  ('Christmas Island', 'CX'),
  ('Cocos (Keeling) Islands', 'CC'),
  ('Colombia', 'CO'),
  ('Comoros', 'KM'),
  ('Congo', 'CG'),
  ('Cook Islands', 'CK'),
  ('Costa Rica', 'CR'),
  ('Croatia', 'HR'),
  ('Cuba', 'CU'),
  ('Cyprus', 'CY'),
  ('Czech Republic', 'CZ'),
  ('Denmark', 'DK'),
  ('Djibouti', 'DJ'),
  ('Dominica', 'DM'),
  ('Dominican Republic', 'DO'),
  ('Ecuador', 'EC'),
  ('Egypt', 'EG'),
  ('El Salvador', 'SV'),
  ('Equatorial Guinea', 'GQ'),
  ('Eritrea', 'ER'),
  ('Estonia', 'EE'),
  ('Ethiopia', 'ET'),
  ('Falkland Islands (Malvinas)', 'FK'),
  ('Faroe Islands', 'FO'),
  ('Fiji', 'FJ'),
  ('Finland', 'FI'),
  ('France', 'FR'),
  ('French Guiana', 'GF'),
  ('French Polynesia', 'PF'),
  ('French Southern Territories', 'TF'),
  ('Gabon', 'GA'),
  ('Gambia', 'GM'),
  ('Georgia', 'GE'),
  ('Germany', 'DE'),
  ('Ghana', 'GH'),
  ('Gibraltar', 'GI'),
  ('Greece', 'GR'),
  ('Greenland', 'GL'),
  ('Grenada', 'GD'),
  ('Guadeloupe', 'GP'),
  ('Guam', 'GU'),
  ('Guatemala', 'GT'),
  ('Guernsey', 'GG'),
  ('Guinea', 'GN'),
  ('Guinea-Bissau', 'GW'),
  ('Guyana', 'GY'),
  ('Haiti', 'HT'),
  ('Heard Island and McDonald Islands', 'HM'),
  ('Holy See (Vatican City State)', 'VA'),
  ('Honduras', 'HN'),
  ('Hong Kong', 'HK'),
  ('Hungary', 'HU'),
  ('Iceland', 'IS'),
  ('India', 'IN'),
  ('Indonesia', 'ID'),
  ('Iraq', 'IQ'),
  ('Ireland', 'IE'),
  ('Isle of Man', 'IM'),
  ('Israel', 'IL'),
  ('Italy', 'IT'),
  ('Jamaica', 'JM'),
  ('Japan', 'JP'),
  ('Jersey', 'JE'),
  ('Jordan', 'JO'),
  ('Kazakhstan', 'KZ'),
  ('Kenya', 'KE'),
  ('Kiribati', 'KI'),
  ('Kuwait', 'KW'),
  ('Kyrgyzstan', 'KG'),
  ('Lao Peoples Democratic Republic', 'LA'),
  ('Latvia', 'LV'),
  ('Lebanon', 'LB'),
  ('Lesotho', 'LS'),
  ('Liberia', 'LR'),
  ('Libya', 'LY'),
  ('Liechtenstein', 'LI'),
  ('Lithuania', 'LT'),
  ('Luxembourg', 'LU'),
  ('Macao', 'MO'),
  ('Madagascar', 'MG'),
  ('Malawi', 'MW'),
  ('Malaysia', 'MY'),
  ('Maldives', 'MV'),
  ('Mali', 'ML'),
  ('Malta', 'MT'),
  ('Marshall Islands', 'MH'),
  ('Martinique', 'MQ'),
  ('Mauritania', 'MR'),
  ('Mauritius', 'MU'),
  ('Mayotte', 'YT'),
  ('Mexico', 'MX'),
  ('Monaco', 'MC'),
  ('Mongolia', 'MN'),
  ('Montenegro', 'ME'),
  ('Montserrat', 'MS'),
  ('Morocco', 'MA'),
  ('Mozambique', 'MZ'),
  ('Myanmar', 'MM'),
  ('Namibia', 'NA'),
  ('Nauru', 'NR'),
  ('Nepal', 'NP'),
  ('Netherlands', 'NL'),
  ('New Caledonia', 'NC'),
  ('New Zealand', 'NZ'),
  ('Nicaragua', 'NI'),
  ('Niger', 'NE'),
  ('Nigeria', 'NG'),
  ('Niue', 'NU'),
  ('Norfolk Island', 'NF'),
  ('Northern Mariana Islands', 'MP'),
  ('Norway', 'NO'),
  ('Oman', 'OM'),
  ('Pakistan', 'PK'),
  ('Palau', 'PW'),
  ('Panama', 'PA'),
  ('Papua New Guinea', 'PG'),
  ('Paraguay', 'PY'),
  ('Peru', 'PE'),
  ('Philippines', 'PH'),
  ('Pitcairn', 'PN'),
  ('Poland', 'PL'),
  ('Portugal', 'PT'),
  ('Puerto Rico', 'PR'),
  ('Qatar', 'QA'),
  ('Romania', 'RO'),
  ('Russian Federation', 'RU'),
  ('Rwanda', 'RW'),
  ('Saint Kitts and Nevis', 'KN'),
  ('Saint Lucia', 'LC'),
  ('Saint Martin (French part)', 'MF'),
  ('Saint Pierre and Miquelon', 'PM'),
  ('Saint Vincent and the Grenadines', 'VC'),
  ('Samoa', 'WS'),
  ('San Marino', 'SM'),
  ('Sao Tome and Principe', 'ST'),
  ('Saudi Arabia', 'SA'),
  ('Senegal', 'SN'),
  ('Serbia', 'RS'),
  ('Seychelles', 'SC'),
  ('Sierra Leone', 'SL'),
  ('Singapore', 'SG'),
  ('Sint Maarten (Dutch part)', 'SX'),
  ('Slovakia', 'SK'),
  ('Slovenia', 'SI'),
  ('Solomon Islands', 'SB'),
  ('Somalia', 'SO'),
  ('South Africa', 'ZA'),
  (
    'South Georgia and the South Sandwich Islands',
    'GS'
  ),
  ('South Sudan', 'SS'),
  ('Spain', 'ES'),
  ('Sri Lanka', 'LK'),
  ('Sudan', 'SD'),
  ('Suriname', 'SR'),
  ('Svalbard and Jan Mayen', 'SJ'),
  ('Swaziland', 'SZ'),
  ('Sweden', 'SE'),
  ('Switzerland', 'CH'),
  ('Syrian Arab Republic', 'SY'),
  ('Tajikistan', 'TJ'),
  ('Thailand', 'TH'),
  ('Timor-Leste', 'TL'),
  ('Togo', 'TG'),
  ('Tokelau', 'TK'),
  ('Tonga', 'TO'),
  ('Trinidad and Tobago', 'TT'),
  ('Tunisia', 'TN'),
  ('Turkey', 'TR'),
  ('Turkmenistan', 'TM'),
  ('Turks and Caicos Islands', 'TC'),
  ('Tuvalu', 'TV'),
  ('Uganda', 'UG'),
  ('Ukraine', 'UA'),
  ('United Arab Emirates', 'AE'),
  ('United Kingdom', 'GB'),
  ('United States', 'US'),
  ('United States Minor Outlying Islands', 'UM'),
  ('Uruguay', 'UY'),
  ('Uzbekistan', 'UZ'),
  ('Vanuatu', 'VU'),
  ('Viet Nam', 'VN'),
  ('Wallis and Futuna', 'WF'),
  ('Western Sahara', 'EH'),
  ('Yemen', 'YE'),
  ('Zambia', 'ZM'),
  ('Zimbabwe', 'ZW');
-- -----------------------------------------------------
-- Dumping data Profile
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Profile` (
    user_id,
    image,
    public_id,
    firstname,
    lastname,
    dob,
    country_id
  )
VALUES (
    1,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630948899/stampee/users/xb89hbmamlgqpvw2qirv.jpg',
    'e2095613/users/xb89hbmamlgqpvw2qirv',
    'Joel',
    'Ramirez',
    '1980-09-06',
    134
  ),
  (
    2,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630956751/stampee/users/yk3rj6k6expxqsdyivih.jpg',
    'e2095613/users/yk3rj6k6expxqsdyivih',
    'Pierrick',
    'Le Roy',
    '1977-08-22',
    70
  ),
  (
    3,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630695701/stampee/users/default_profile.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    4,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630695701/stampee/users/default_profile.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
-- -----------------------------------------------------
-- Dumping data Filters
-- -----------------------------------------------------
INSERT INTO `Filters` (
    `user_id`,
    `theme_id`,
    `country_id`,
    `category_id`
  )
VALUES (1, NULL, NULL, NULL),
  (2, NULL, NULL, NULL),
  (3, NULL, NULL, NULL),
  (4, NULL, NULL, NULL);
-- -----------------------------------------------------
-- Dumping data StampCondition
-- -----------------------------------------------------
INSERT INTO `e2095613`.`StampCondition`(name)
VALUES('parfaite'),
  ('excellente'),
  ('bonne'),
  ('moyenne'),
  ('endommagée');
-- -----------------------------------------------------
-- Dumping data Category
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Category`(name)
VALUES("timbres d'usage courant"),
  ("timbres commémoratifs"),
  ("timbres avec surtaxe"),
  ("timbres de poste aérienne"),
  ("timbres préoblitérés"),
  ("timbres taxe"),
  ("timbres de service"),
  ("timbres-télégraphe"),
  ("timbres de grève");
-- -----------------------------------------------------
-- Dumping data Theme
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Theme`(name)
VALUES("Abeilles"),
  ("Afrique"),
  ("Agriculture"),
  ("Aliments"),
  ("Allemagne"),
  ("Alpinisme et montagnes"),
  ("Ange"),
  ("Animaux"),
  ("Animaux préhistoriques"),
  ("Animaux sauvages"),
  ("Anti-racisme"),
  ("Arbres et forets"),
  ("Archeologie"),
  ("Architectes"),
  ("Architecture"),
  ("Armee Du Salut"),
  ("Armes"),
  ("Art"),
  ("Artisanat"),
  ("Astronomie"),
  ("Athletisme"),
  ("Auteurs Et Poetes"),
  ("Autos"),
  ("Avions Et Navigation Aerienne"),
  ("Ballons Atmospheriques"),
  ("Bandes Dessinees"),
  ("Base-ball"),
  ("Basketball"),
  ("Bateaux Et Navigation"),
  ("Bibliotheques"),
  ("Bicyclettes, Coureurs Etc."),
  ("Billard"),
  ("Bonzai"),
  ("Boxer"),
  ("Cartes Geographiques"),
  ("Cerf-volant"),
  ("Champignons"),
  ("Chats"),
  ("Chevaliers"),
  ("Chevaux"),
  ("Chiens"),
  ("Chimie Et Chimistes"),
  ("Cinéma"),
  ("Churchill"),
  ("Citadelles, Chateaux Et Palais"),
  ("Contes, Fables Et Legendes"),
  ("Coquilles Et Crustacés"),
  ("Costumes"),
  ("Crocodiles"),
  ("Croix Rouge"),
  ("deuxième guerre mondiale"),
  ("Disney"),
  ("Divers"),
  ("Drapeaux"),
  ("Droit Et Loi"),
  ("Droits De L’homme"),
  ("Eglises, Temples, Mosquees Et Synagogues"),
  ("Elephants"),
  ("Elvis Presley"),
  ("Emancipation"),
  ("Energie"),
  ("Enseignement Et Education"),
  ("Escrime"),
  ("Europe"),
  ("Evenements Historiques"),
  ("Explorateurs"),
  ("Expositions Mondial"),
  ("Ferrari"),
  ("Film"),
  ("Fleurs Et Plantes"),
  ("Folklore"),
  ("Football"),
  ("Fruits"),
  ("Gandhi"),
  ("Golf"),
  ("Greenpeace"),
  ("Grenouilles Et Crapauds"),
  ("Gymnastique"),
  ("Haloween"),
  ("Hand-ball"),
  ("Handicapes"),
  ("Harry Potter"),
  ("Helicopteres"),
  ("Henri De Toulouse-Lautrec"),
  ("Heritage Du Monde"),
  ("Hibous"),
  ("Hippopotame"),
  ("Histoire"),
  ("Hockey"),
  ("Imprimerie"),
  ("Industrie"),
  ("Insectes"),
  ("Instruments De Musique"),
  ("Inventeurs"),
  ("Islam"),
  ("Jardins"),
  ("Jeux Olympiques"),
  ("Journaux et Journalisme"),
  ("Judo"),
  ("Juifs"),
  ("Jules Verne"),
  ("Leonardo Da Vinci"),
  ("Livres"),
  ("Marilyn Monroe"),
  ("Michael Jackson"),
  ("Mode"),
  ("Monastères et Abbayes"),
  ("Moulins"),
  ("Museés"),
  ("Musique"),
  ("Musique Jazz"),
  ("Musique Populaire"),
  ("Napolèon"),
  ("Natation"),
  ("Nature"),
  ("Nelson Mandela"),
  ("Noel"),
  ("Nouvel An"),
  ("Oiseaux"),
  ("Orchidées"),
  ("Ordinateurs"),
  ("Pablo Picasso"),
  ("Paix"),
  ("Papillons"),
  ("Parachutisme"),
  ("Patinage"),
  ("Pêche"),
  ("Peintres"),
  ("Penguins"),
  ("Perroquet"),
  ("Phares"),
  ("Photographie"),
  ("Physiciens"),
  ("Poids et Haltères"),
  ("Poissons"),
  ("Police"),
  ("Politiciens"),
  ("Ponts et Tunnels"),
  ("Présidents des Etats-Unis"),
  ("Presidents Francais"),
  ("Protection de l’environnement"),
  ("Radio/Télévision"),
  ("Rapaces"),
  ("Religion"),
  ("Rembrandt"),
  ("Reptiles"),
  ("Révolution Russe"),
  ("Rhinocèros"),
  ("Roses"),
  ("Rugby"),
  ("Salvador Dali"),
  ("Santé"),
  ("Science"),
  ("Science-fiction"),
  ("Scoutisme"),
  ("Sculptures"),
  ("Serpents"),
  ("Sida"),
  ("Singes"),
  ("Ski"),
  ("Sport"),
  ("Tennis"),
  ("TinTin"),
  ("Tortue"),
  ("Tourisme"),
  ("Trains"),
  ("Transport"),
  ("Uniformes"),
  ("Vedettes du Cinéma"),
  ("Vincent Van Gogh"),
  ("Vins et Viticulture"),
  ("Vitraux et Fenêtres");
-- -----------------------------------------------------
-- Dumping data Auction
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Auction` (
    id,
    name,
    description,
    start_date,
    end_date,
    start_price,
    published,
    createdAt,
    user_id
  )
VALUES (
    1,
    'Elvis Presley Très Rare à ne pas manquer!',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    '2021-09-03 20:48:00',
    '2021-09-06 00:00:00',
    100,
    1,
    '2021-09-06 00:48:52',
    1
  ),
  (
    2,
    'Marilyn Monroe Forever Stamp',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    '2021-08-29 02:21:00',
    '2021-09-03 02:21:00',
    200,
    1,
    '2021-09-06 06:21:55',
    1
  ),
  (
    3,
    'Star Wars Collection 3 Items',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    '2021-09-13 14:26:00',
    '2021-09-20 14:26:00',
    80,
    1,
    '2021-09-06 18:27:02',
    2
  ),
  (
    4,
    'Collection 50 ans de 2001 A Space Odyssey',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    '2021-09-05 12:00:00',
    '2021-09-19 12:00:00',
    50,
    1,
    '2021-09-06 19:24:16',
    2
  );
-- -----------------------------------------------------
-- Dumping data Stamp
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Stamp` (
    id,
    name,
    description,
    year,
    width,
    height,
    createdAt,
    country_id,
    category_id,
    condition_id,
    user_id,
    theme_id,
    auction_id
  )
VALUES (
    1,
    'Elvis Presley',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    1967,
    800,
    600,
    '2021-09-06 00:48:03',
    218,
    1,
    1,
    1,
    43,
    1
  ),
  (
    2,
    'Marilyn Monroe',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    1980,
    500,
    800,
    '2021-09-06 06:21:25',
    189,
    1,
    2,
    1,
    169,
    2
  ),
  (
    7,
    'Hans Solo',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    2017,
    600,
    600,
    '2021-09-06 18:24:32',
    217,
    1,
    1,
    2,
    43,
    3
  ),
  (
    8,
    'Dark Vador',
    'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    2017,
    600,
    600,
    '2021-09-06 18:25:32',
    217,
    1,
    1,
    2,
    43,
    3
  ),
  (
    9,
    'Yoda',
    'quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    2017,
    600,
    600,
    '2021-09-06 18:26:20',
    217,
    1,
    1,
    2,
    43,
    3
  ),
  (
    14,
    'Mickey Mouse 41',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    1990,
    777,
    888,
    '2021-09-06 19:16:08',
    218,
    1,
    2,
    2,
    52,
    NULL
  ),
  (
    15,
    '50 ans de 2001 A Space Odyssey 83 pennies',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    2018,
    600,
    800,
    '2021-09-06 19:17:03',
    101,
    1,
    1,
    2,
    43,
    4
  ),
  (
    16,
    '50 ans de 2001 A Space Odyssey 1.93',
    ' Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    2018,
    600,
    800,
    '2021-09-06 19:17:56',
    101,
    1,
    1,
    2,
    43,
    4
  ),
  (
    17,
    '50 ans de 2001 A Space Odyssey 52 pennies',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.',
    2018,
    600,
    800,
    '2021-09-06 19:19:44',
    101,
    1,
    1,
    2,
    43,
    4
  ),
  (
    18,
    '50 ans de 2001 A Space Odyssey 75 pennies',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.',
    2018,
    600,
    800,
    '2021-09-06 19:20:25',
    101,
    1,
    1,
    2,
    43,
    4
  ),
  (
    19,
    '50 ans de 2001 A Space Odyssey 1.40',
    'reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    2018,
    600,
    800,
    '2021-09-06 19:21:13',
    101,
    1,
    1,
    2,
    43,
    4
  ),
  (
    20,
    '50 ans de 2001 A Space Odyssey 2.01',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamc.',
    2018,
    600,
    800,
    '2021-09-06 19:22:18',
    101,
    1,
    1,
    2,
    43,
    4
  );
-- -----------------------------------------------------
-- Dumping data Image
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Image` (stamp_id, url, public_id)
VALUES (
    1,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630889282/stampee/stamps/khtw54d58fnim6rmpepb.webp',
    'e2095613/stamps/khtw54d58fnim6rmpepb'
  ),
  (
    2,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630909285/stampee/stamps/rnqyts6tkkk94jqctqy7.jpg',
    'e2095613/stamps/rnqyts6tkkk94jqctqy7'
  ),
  (
    7,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630952671/stampee/stamps/yevjltqoehupr0lzcunm.jpg',
    'e2095613/stamps/yevjltqoehupr0lzcunm'
  ),
  (
    8,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630952732/stampee/stamps/mupa92stklhibpxyyfpp.jpg',
    'e2095613/stamps/mupa92stklhibpxyyfpp'
  ),
  (
    9,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630952779/stampee/stamps/yev8ui52buvhjpsb9wro.jpg',
    'e2095613/stamps/yev8ui52buvhjpsb9wro'
  ),
  (
    14,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630955768/stampee/stamps/kosad8waiofskliyhukq.jpg',
    'e2095613/stamps/kosad8waiofskliyhukq'
  ),
  (
    15,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630955822/stampee/stamps/qm8l7szegntgv8z3eugc.jpg',
    'e2095613/stamps/qm8l7szegntgv8z3eugc'
  ),
  (
    16,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630955875/stampee/stamps/qcpb8gozjujaukxyvgi6.jpg',
    'e2095613/stamps/qcpb8gozjujaukxyvgi6'
  ),
  (
    17,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630955984/stampee/stamps/htloktvzkcpxydb08hja.jpg',
    'e2095613/stamps/htloktvzkcpxydb08hja'
  ),
  (
    18,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630956024/stampee/stamps/l7cpqcsfvstnodkyhemv.jpg',
    'e2095613/stamps/l7cpqcsfvstnodkyhemv'
  ),
  (
    19,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630956073/stampee/stamps/ybtpz2jdo04s0c2geqiu.jpg',
    'e2095613/stamps/ybtpz2jdo04s0c2geqiu'
  ),
  (
    20,
    'https://res.cloudinary.com/dwhnxncff/image/upload/v1630956137/stampee/stamps/a4iunzoyypjqpqpmbaht.jpg',
    'e2095613/stamps/a4iunzoyypjqpqpmbaht'
  );
-- -----------------------------------------------------
-- Dumping data Offer
-- -----------------------------------------------------
INSERT INTO `e2095613`.`Offer` (
    id,
    user_id,
    auction_id,
    current_price,
    createdAt
  )
VALUES (1, 2, 1, 120, '2021-09-06 00:51:35'),
  (5, 3, 1, 160, '2021-09-06 01:10:34'),
  (6, 2, 1, 190, '2021-09-06 01:18:20'),
  (7, 3, 1, 250, '2021-09-06 01:19:52'),
  (8, 1, 4, 70, '2021-09-06 19:46:03'),
  (9, 4, 4, 99, '2021-09-06 19:49:26');