-- MySQL Script generated by MySQL Workbench
-- Fri Aug 27 10:02:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema stampee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stampee` DEFAULT CHARACTER SET utf8;
USE `stampee`;
-- -----------------------------------------------------
-- Table `stampee`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Role` (
  `id` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_id` TINYINT DEFAULT 1,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Country` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL UNIQUE,
  `iso` CHAR(2) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Profile` (
  `user_id` INT UNSIGNED NOT NULL,
  `image` VARCHAR(255) DEFAULT 'https://res.cloudinary.com/dwhnxncff/image/upload/v1630162777/stampee/users/avatar.png',
  `country_id` TINYINT UNSIGNED NULL,
  INDEX `fk_Profile_Country_idx` (`country_id` ASC),
  INDEX `fk_Profile_User_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_Profil_Country1` FOREIGN KEY (`country_id`) REFERENCES `stampee`.`Country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_User1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`ResetPasswordToken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`ResetPasswordToken` (
  `token` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `user_Id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`token`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  INDEX `belongsTo_idx` (`user_Id` ASC),
  CONSTRAINT `belongsTo` FOREIGN KEY (`user_Id`) REFERENCES `stampee`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Category` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`StampCondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`StampCondition` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Theme` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Stamp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Stamp` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `year` YEAR NOT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `certified` TINYINT(1) NULL,
  `country_id` TINYINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `condition_id` TINYINT UNSIGNED NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `theme_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stamp_Country_idx` (`country_id` ASC),
  INDEX `fk_Stamp_Category_idx` (`category_id` ASC),
  INDEX `fk_Stamp_Condition_idx` (`condition_id` ASC),
  INDEX `fk_Stamp_User_idx` (`user_id` ASC),
  INDEX `fk_Stamp_Theme_idx` (`theme_id` ASC),
  CONSTRAINT `fk_Stamp_Country1` FOREIGN KEY (`country_id`) REFERENCES `stampee`.`Country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_Category1` FOREIGN KEY (`category_id`) REFERENCES `stampee`.`Category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_Condition1` FOREIGN KEY (`condition_id`) REFERENCES `stampee`.`StampCondition` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_User1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stamp_Theme1` FOREIGN KEY (`theme_id`) REFERENCES `stampee`.`Theme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Auction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `start_price` INT NOT NULL,
  `published` TINYINT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `image` TINYTEXT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `stamp_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Auction_User1_idx` (`user_id` ASC),
  INDEX `fk_Auction_Stamp1_idx` (`stamp_id` ASC),
  CONSTRAINT `fk_Auction_User1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_Stamp1` FOREIGN KEY (`stamp_id`) REFERENCES `stampee`.`Stamp` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `stampee`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `auction_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_Auction1_idx` (`auction_id` ASC),
  INDEX `fk_Comment_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Comment_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `stampee`.`Auction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_User1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TINYTEXT NOT NULL,
  `public_id` TINYTEXT NOT NULL,
  `stamp_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Image_Stamp1_idx` (`stamp_id` ASC),
  CONSTRAINT `fk_Image_Stamp1` FOREIGN KEY (`stamp_id`) REFERENCES `stampee`.`Stamp` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Offer` (
  `user_id` INT UNSIGNED NOT NULL,
  `auction_id` INT UNSIGNED NOT NULL,
  `current_price` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `auction_id`),
  INDEX `fk_Offer_Auction1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_Offer_User1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`User` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offer_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `stampee`.`Auction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Follow` (
  `user_id` INT UNSIGNED NOT NULL,
  `follower_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `follower_id`),
  INDEX `fk_Follow_Profile2_idx` (`follower_id` ASC),
  CONSTRAINT `fk_Follow_Profile1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Follow_Profile2` FOREIGN KEY (`follower_id`) REFERENCES `stampee`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `stampee`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`Favorites` (
  `user_id` INT UNSIGNED NOT NULL,
  `auction_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `auction_id`),
  INDEX `fk_Favorites_Auction1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_Favorites_Profile1` FOREIGN KEY (`user_id`) REFERENCES `stampee`.`Profile` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_Auction1` FOREIGN KEY (`auction_id`) REFERENCES `stampee`.`Auction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
-- -----------------------------------------------------
-- Dumping data Role
-- -----------------------------------------------------
INSERT INTO `stampee`.`Role`(id, name)
VALUES(1, "Membre"),
  (2, "Administrateur");
-- -----------------------------------------------------
-- Dumping data Country
-- -----------------------------------------------------
INSERT INTO `stampee`.`Country`(name, iso)
VALUES ('Afghanistan', 'AF'),
  ('Albania', 'AL'),
  ('Algeria', 'DZ'),
  ('American Samoa', 'AS'),
  ('Andorra', 'AD'),
  ('Angola', 'AO'),
  ('Anguilla', 'AI'),
  ('Antarctica', 'AQ'),
  ('Antigua and Barbuda', 'AG'),
  ('Argentina', 'AR'),
  ('Armenia', 'AM'),
  ('Aruba', 'AW'),
  ('Australia', 'AU'),
  ('Austria', 'AT'),
  ('Azerbaijan', 'AZ'),
  ('Bahamas', 'BS'),
  ('Bahrain', 'BH'),
  ('Bangladesh', 'BD'),
  ('Barbados', 'BB'),
  ('Belarus', 'BY'),
  ('Belgium', 'BE'),
  ('Belize', 'BZ'),
  ('Benin', 'BJ'),
  ('Bermuda', 'BM'),
  ('Bhutan', 'BT'),
  ('Bosnia and Herzegovina', 'BA'),
  ('Botswana', 'BW'),
  ('Bouvet Island', 'BV'),
  ('Brazil', 'BR'),
  ('British Indian Ocean Territory', 'IO'),
  ('Brunei Darussalam', 'BN'),
  ('Bulgaria', 'BG'),
  ('Burkina Faso', 'BF'),
  ('Burundi', 'BI'),
  ('Cambodia', 'KH'),
  ('Cameroon', 'CM'),
  ('Canada', 'CA'),
  ('Cape Verde', 'CV'),
  ('Cayman Islands', 'KY'),
  ('Central African Republic', 'CF'),
  ('Chad', 'TD'),
  ('Chile', 'CL'),
  ('China', 'CN'),
  ('Christmas Island', 'CX'),
  ('Cocos (Keeling) Islands', 'CC'),
  ('Colombia', 'CO'),
  ('Comoros', 'KM'),
  ('Congo', 'CG'),
  ('Cook Islands', 'CK'),
  ('Costa Rica', 'CR'),
  ('Croatia', 'HR'),
  ('Cuba', 'CU'),
  ('Cyprus', 'CY'),
  ('Czech Republic', 'CZ'),
  ('Denmark', 'DK'),
  ('Djibouti', 'DJ'),
  ('Dominica', 'DM'),
  ('Dominican Republic', 'DO'),
  ('Ecuador', 'EC'),
  ('Egypt', 'EG'),
  ('El Salvador', 'SV'),
  ('Equatorial Guinea', 'GQ'),
  ('Eritrea', 'ER'),
  ('Estonia', 'EE'),
  ('Ethiopia', 'ET'),
  ('Falkland Islands (Malvinas)', 'FK'),
  ('Faroe Islands', 'FO'),
  ('Fiji', 'FJ'),
  ('Finland', 'FI'),
  ('France', 'FR'),
  ('French Guiana', 'GF'),
  ('French Polynesia', 'PF'),
  ('French Southern Territories', 'TF'),
  ('Gabon', 'GA'),
  ('Gambia', 'GM'),
  ('Georgia', 'GE'),
  ('Germany', 'DE'),
  ('Ghana', 'GH'),
  ('Gibraltar', 'GI'),
  ('Greece', 'GR'),
  ('Greenland', 'GL'),
  ('Grenada', 'GD'),
  ('Guadeloupe', 'GP'),
  ('Guam', 'GU'),
  ('Guatemala', 'GT'),
  ('Guernsey', 'GG'),
  ('Guinea', 'GN'),
  ('Guinea-Bissau', 'GW'),
  ('Guyana', 'GY'),
  ('Haiti', 'HT'),
  ('Heard Island and McDonald Islands', 'HM'),
  ('Holy See (Vatican City State)', 'VA'),
  ('Honduras', 'HN'),
  ('Hong Kong', 'HK'),
  ('Hungary', 'HU'),
  ('Iceland', 'IS'),
  ('India', 'IN'),
  ('Indonesia', 'ID'),
  ('Iraq', 'IQ'),
  ('Ireland', 'IE'),
  ('Isle of Man', 'IM'),
  ('Israel', 'IL'),
  ('Italy', 'IT'),
  ('Jamaica', 'JM'),
  ('Japan', 'JP'),
  ('Jersey', 'JE'),
  ('Jordan', 'JO'),
  ('Kazakhstan', 'KZ'),
  ('Kenya', 'KE'),
  ('Kiribati', 'KI'),
  ('Kuwait', 'KW'),
  ('Kyrgyzstan', 'KG'),
  ('Lao Peoples Democratic Republic', 'LA'),
  ('Latvia', 'LV'),
  ('Lebanon', 'LB'),
  ('Lesotho', 'LS'),
  ('Liberia', 'LR'),
  ('Libya', 'LY'),
  ('Liechtenstein', 'LI'),
  ('Lithuania', 'LT'),
  ('Luxembourg', 'LU'),
  ('Macao', 'MO'),
  ('Madagascar', 'MG'),
  ('Malawi', 'MW'),
  ('Malaysia', 'MY'),
  ('Maldives', 'MV'),
  ('Mali', 'ML'),
  ('Malta', 'MT'),
  ('Marshall Islands', 'MH'),
  ('Martinique', 'MQ'),
  ('Mauritania', 'MR'),
  ('Mauritius', 'MU'),
  ('Mayotte', 'YT'),
  ('Mexico', 'MX'),
  ('Monaco', 'MC'),
  ('Mongolia', 'MN'),
  ('Montenegro', 'ME'),
  ('Montserrat', 'MS'),
  ('Morocco', 'MA'),
  ('Mozambique', 'MZ'),
  ('Myanmar', 'MM'),
  ('Namibia', 'NA'),
  ('Nauru', 'NR'),
  ('Nepal', 'NP'),
  ('Netherlands', 'NL'),
  ('New Caledonia', 'NC'),
  ('New Zealand', 'NZ'),
  ('Nicaragua', 'NI'),
  ('Niger', 'NE'),
  ('Nigeria', 'NG'),
  ('Niue', 'NU'),
  ('Norfolk Island', 'NF'),
  ('Northern Mariana Islands', 'MP'),
  ('Norway', 'NO'),
  ('Oman', 'OM'),
  ('Pakistan', 'PK'),
  ('Palau', 'PW'),
  ('Panama', 'PA'),
  ('Papua New Guinea', 'PG'),
  ('Paraguay', 'PY'),
  ('Peru', 'PE'),
  ('Philippines', 'PH'),
  ('Pitcairn', 'PN'),
  ('Poland', 'PL'),
  ('Portugal', 'PT'),
  ('Puerto Rico', 'PR'),
  ('Qatar', 'QA'),
  ('Romania', 'RO'),
  ('Russian Federation', 'RU'),
  ('Rwanda', 'RW'),
  ('Saint Kitts and Nevis', 'KN'),
  ('Saint Lucia', 'LC'),
  ('Saint Martin (French part)', 'MF'),
  ('Saint Pierre and Miquelon', 'PM'),
  ('Saint Vincent and the Grenadines', 'VC'),
  ('Samoa', 'WS'),
  ('San Marino', 'SM'),
  ('Sao Tome and Principe', 'ST'),
  ('Saudi Arabia', 'SA'),
  ('Senegal', 'SN'),
  ('Serbia', 'RS'),
  ('Seychelles', 'SC'),
  ('Sierra Leone', 'SL'),
  ('Singapore', 'SG'),
  ('Sint Maarten (Dutch part)', 'SX'),
  ('Slovakia', 'SK'),
  ('Slovenia', 'SI'),
  ('Solomon Islands', 'SB'),
  ('Somalia', 'SO'),
  ('South Africa', 'ZA'),
  (
    'South Georgia and the South Sandwich Islands',
    'GS'
  ),
  ('South Sudan', 'SS'),
  ('Spain', 'ES'),
  ('Sri Lanka', 'LK'),
  ('Sudan', 'SD'),
  ('Suriname', 'SR'),
  ('Svalbard and Jan Mayen', 'SJ'),
  ('Swaziland', 'SZ'),
  ('Sweden', 'SE'),
  ('Switzerland', 'CH'),
  ('Syrian Arab Republic', 'SY'),
  ('Tajikistan', 'TJ'),
  ('Thailand', 'TH'),
  ('Timor-Leste', 'TL'),
  ('Togo', 'TG'),
  ('Tokelau', 'TK'),
  ('Tonga', 'TO'),
  ('Trinidad and Tobago', 'TT'),
  ('Tunisia', 'TN'),
  ('Turkey', 'TR'),
  ('Turkmenistan', 'TM'),
  ('Turks and Caicos Islands', 'TC'),
  ('Tuvalu', 'TV'),
  ('Uganda', 'UG'),
  ('Ukraine', 'UA'),
  ('United Arab Emirates', 'AE'),
  ('United Kingdom', 'GB'),
  ('United States', 'US'),
  ('United States Minor Outlying Islands', 'UM'),
  ('Uruguay', 'UY'),
  ('Uzbekistan', 'UZ'),
  ('Vanuatu', 'VU'),
  ('Viet Nam', 'VN'),
  ('Wallis and Futuna', 'WF'),
  ('Western Sahara', 'EH'),
  ('Yemen', 'YE'),
  ('Zambia', 'ZM'),
  ('Zimbabwe', 'ZW');
-- -----------------------------------------------------
-- Dumping data StampCondition
-- -----------------------------------------------------
INSERT INTO `stampee`.`StampCondition`(name)
VALUES('parfaite'),
  ('excellente'),
  ('bonne'),
  ('moyenne'),
  ('endommagée');
-- -----------------------------------------------------
-- Dumping data Category
-- -----------------------------------------------------
INSERT INTO `stampee`.`Category`(name)
VALUES("timbres d'usage courant"),
  ("timbres commémoratifs"),
  ("timbres avec surtaxe"),
  ("timbres de poste aérienne"),
  ("timbres préoblitérés"),
  ("timbres taxe"),
  ("timbres de service"),
  ("timbres-télégraphe"),
  ("timbres de grève");
-- -----------------------------------------------------
-- Dumping data Theme
-- -----------------------------------------------------
INSERT INTO `stampee`.`Theme`(name)
VALUES("Abeilles"),
  ("Afrique"),
  ("Agriculture"),
  ("Aliments"),
  ("Allemagne"),
  ("Alpinisme et montagnes"),
  ("Ange"),
  ("Animaux"),
  ("Animaux préhistoriques"),
  ("Animaux sauvages"),
  ("Anti-racisme"),
  ("Arbres et forets"),
  ("Archeologie"),
  ("Architectes"),
  ("Architecture"),
  ("Armee Du Salut"),
  ("Armes"),
  ("Art"),
  ("Artisanat"),
  ("Astronomie"),
  ("Athletisme"),
  ("Auteurs Et Poetes"),
  ("Autos"),
  ("Avions Et Navigation Aerienne"),
  ("Ballons Atmospheriques"),
  ("Bandes Dessinees"),
  ("Base-ball"),
  ("Basketball"),
  ("Bateaux Et Navigation"),
  ("Bibliotheques"),
  ("Bicyclettes, Coureurs Etc."),
  ("Billard"),
  ("Bonzai"),
  ("Boxer"),
  ("Cartes Geographiques"),
  ("Cerf-volant"),
  ("Champignons"),
  ("Chats"),
  ("Chevaliers"),
  ("Chevaux"),
  ("Chiens"),
  ("Chimie Et Chimistes"),
  ("Churchill"),
  ("Citadelles, Chateaux Et Palais"),
  ("Contes, Fables Et Legendes"),
  ("Coquilles Et Crustacés"),
  ("Costumes"),
  ("Crocodiles"),
  ("Croix Rouge"),
  ("deuxième guerre mondiale"),
  ("Disney"),
  ("Divers"),
  ("Drapeaux"),
  ("Droit Et Loi"),
  ("Droits De L’homme"),
  ("Eglises, Temples, Mosquees Et Synagogues"),
  ("Elephants"),
  ("Elvis Presley"),
  ("Emancipation"),
  ("Energie"),
  ("Enseignement Et Education"),
  ("Escrime"),
  ("Europe"),
  ("Evenements Historiques"),
  ("Explorateurs"),
  ("Expositions Mondial"),
  ("Ferrari"),
  ("Film"),
  ("Fleurs Et Plantes"),
  ("Folklore"),
  ("Football"),
  ("Fruits"),
  ("Gandhi"),
  ("Golf"),
  ("Greenpeace"),
  ("Grenouilles Et Crapauds"),
  ("Gymnastique"),
  ("Haloween"),
  ("Hand-ball"),
  ("Handicapes"),
  ("Harry Potter"),
  ("Helicopteres"),
  ("Henri De Toulouse-Lautrec"),
  ("Heritage Du Monde"),
  ("Hibous"),
  ("Hippopotame"),
  ("Histoire"),
  ("Hockey"),
  ("Imprimerie"),
  ("Industrie"),
  ("Insectes"),
  ("Instruments De Musique"),
  ("Inventeurs"),
  ("Islam"),
  ("Jardins"),
  ("Jeux Olympiques"),
  ("Journaux et Journalisme"),
  ("Judo"),
  ("Juifs"),
  ("Jules Verne"),
  ("Leonardo Da Vinci"),
  ("Livres"),
  ("Marilyn Monroe"),
  ("Michael Jackson"),
  ("Mode"),
  ("Monastères et Abbayes"),
  ("Moulins"),
  ("Museés"),
  ("Musique"),
  ("Musique Jazz"),
  ("Musique Populaire"),
  ("Napolèon"),
  ("Natation"),
  ("Nature"),
  ("Nelson Mandela"),
  ("Noel"),
  ("Nouvel An"),
  ("Oiseaux"),
  ("Orchidées"),
  ("Ordinateurs"),
  ("Pablo Picasso"),
  ("Paix"),
  ("Papillons"),
  ("Parachutisme"),
  ("Patinage"),
  ("Pêche"),
  ("Peintres"),
  ("Penguins"),
  ("Perroquet"),
  ("Phares"),
  ("Photographie"),
  ("Physiciens"),
  ("Poids et Haltères"),
  ("Poissons"),
  ("Police"),
  ("Politiciens"),
  ("Ponts et Tunnels"),
  ("Présidents des Etats-Unis"),
  ("Presidents Francais"),
  ("Protection de l’environnement"),
  ("Radio/Télévision"),
  ("Rapaces"),
  ("Religion"),
  ("Rembrandt"),
  ("Reptiles"),
  ("Révolution Russe"),
  ("Rhinocèros"),
  ("Roses"),
  ("Rugby"),
  ("Salvador Dali"),
  ("Santé"),
  ("Science"),
  ("Science-fiction"),
  ("Scoutisme"),
  ("Sculptures"),
  ("Serpents"),
  ("Sida"),
  ("Singes"),
  ("Ski"),
  ("Sport"),
  ("Tennis"),
  ("TinTin"),
  ("Tortue"),
  ("Tourisme"),
  ("Trains"),
  ("Transport"),
  ("Uniformes"),
  ("Vedettes du Cinéma"),
  ("Vincent Van Gogh"),
  ("Vins et Viticulture"),
  ("Vitraux et Fenêtres");